<?php

namespace Database\Seeders;

use App\Models\Country;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Country::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $country = [
            [
                "name" => "Bahrain",
                "iso3" => "BHR",
                "numeric_code" => "048",
                "iso2" => "BH",
                "phone_code" => "973",
                "capital" => "Manama",
                "currency" => "BHD",
                "currency_name" => "Bahraini dinar",
                "currency_symbol" => ".د.ب",
                "tld" => ".bh",
                "native" => "\u{200F}البحرين",
                "region" => "Asia",
                "subregion" => "Western Asia",
                "timezones" => '[{"zoneName":"Asia/Bahrain","gmtOffset":10800,"gmtOffsetName":"UTC+03:00","abbreviation":"AST","tzName":"Arabia Standard Time"}]',
                "translations" => '{"kr":"바레인","pt-BR":"Bahrein","pt":"Barém","nl":"Bahrein","hr":"Bahrein","fa":"بحرین","de":"Bahrain","es":"Bahrein","fr":"Bahreïn","ja":"バーレーン","it":"Bahrein","cn":"巴林","tr":"Bahreyn"}',
                "latitude" => "26.00000000",
                "longitude" => "50.55000000",
                "emoji" => "🇧🇭",
                "emojiU" => "U+1F1E7 U+1F1ED",
                "created_at" => "2018-07-21 07:11:03",
                "updated_at" => "2022-05-21 21:11:20",
                "flag" => 1,
                "wikiDataId" => "Q398",
                "created_by" => 1,
                "updated_by"=> null,
                'status' => 1
            ],
            [
                "name" => "Ireland",
                "iso3" => "IRL",
                "numeric_code" => "372",
                "iso2" => "IE",
                "phone_code" => "353",
                "capital" => "Dublin",
                "currency" => "EUR",
                "currency_name" => "Euro",
                "currency_symbol" => "€",
                "tld" => ".ie",
                "native" => "Éire",
                "region" => "Europe",
                "subregion" => "Northern Europe",
                "timezones" => '[{"zoneName":"Europe/Dublin","gmtOffset":0,"gmtOffsetName":"UTC±00","abbreviation":"GMT","tzName":"Greenwich Mean Time"}]',
                "translations" => '{"kr":"아일랜드","pt-BR":"Irlanda","pt":"Irlanda","nl":"Ierland","hr":"Irska","fa":"ایرلند","de":"Irland","es":"Irlanda","fr":"Irlande","ja":"アイルランド","it":"Irlanda","cn":"爱尔兰","tr":"İrlanda"}',
                "latitude" => "53.00000000",
                "longitude" => "-8.00000000",
                "emoji" => "🇮🇪",
                "emojiU" => "U+1F1EE U+1F1EA",
                "created_at" => "2018-07-21 07:11:03",
                "updated_at" => "2022-05-21 21:32:07",
                "flag" => 1,
                "wikiDataId" => "Q27",
                "created_by" => 1,
                "updated_by"=> null,
                'status' => 1
            ],
            [
                "name" => "Kuwait",
                "iso3" => "KWT",
                "numeric_code" => "414",
                "iso2" => "KW",
                "phone_code" => "965",
                "capital" => "Kuwait City",
                "currency" => "KWD",
                "currency_name" => "Kuwaiti dinar",
                "currency_symbol" => "ك.د",
                "tld" => ".kw",
                "native" => "الكويت",
                "region" => "Asia",
                "subregion" => "Western Asia",
                "timezones" => '[{"zoneName":"Asia/Kuwait","gmtOffset":10800,"gmtOffsetName":"UTC+03:00","abbreviation":"AST","tzName":"Arabia Standard Time"}]',
                "translations" => '{"kr":"쿠웨이트","pt-BR":"Kuwait","pt":"Kuwait","nl":"Koeweit","hr":"Kuvajt","fa":"کویت","de":"Kuwait","es":"Kuwait","fr":"Koweït","ja":"クウェート","it":"Kuwait","cn":"科威特","tr":"Kuveyt"}',
                "latitude" => "29.50000000",
                "longitude" => "45.75000000",
                "emoji" => "🇰🇼",
                "emojiU" => "U+1F1F0 U+1F1FC",
                "created_at" => "2018-07-21 07:11:03",
                "updated_at" => "2022-05-21 21:32:07",
                "flag" => 1,
                "wikiDataId" => "Q817",
                "created_by" => 1,
                "updated_by"=> null,
                'status' => 1
            ],
            [
                "name" => "Netherlands",
                "iso3" => "NLD",
                "numeric_code" => "528",
                "iso2" => "NL",
                "phone_code" => "31",
                "capital" => "Amsterdam",
                "currency" => "EUR",
                "currency_name" => "Euro",
                "currency_symbol" => "€",
                "tld" => ".nl",
                "native" => "Nederland",
                "region" => "Europe",
                "subregion" => "Western Europe",
                "timezones" => '[{"zoneName":"Europe/Amsterdam","gmtOffset":3600,"gmtOffsetName":"UTC+01:00","abbreviation":"CET","tzName":"Central European Time"}]',
                "translations" => '{"kr":"네덜란드 ","pt-BR":"Holanda","pt":"Países Baixos","nl":"Nederland","hr":"Nizozemska","fa":"پادشاهی هلند","de":"Niederlande","es":"Países Bajos","fr":"Pays-Bas","ja":"オランダ","it":"Paesi Bassi","cn":"荷兰","tr":"Hollanda"}',
                "latitude" => "52.50000000",
                "longitude" => "5.75000000",
                "emoji" => "🇳🇱",
                "emojiU" => "U+1F1F3 U+1F1F1",
                "created_at" => "2018-07-21 07:11:03",
                "updated_at" => "2022-05-21 21:32:07",
                "flag" => 1,
                "wikiDataId" => "Q55",
                "created_by" => 1,
                "updated_by"=> null,
                'status' => 1
            ],
            [
                "name" => "Pakistan",
                "iso3" => "PAK",
                "numeric_code" => "586",
                "iso2" => "PK",
                "phone_code" => "92",
                "capital" => "Islamabad",
                "currency" => "PKR",
                "currency_name" => "Pakistani rupee",
                "currency_symbol" => "₨",
                "tld" => ".pk",
                "native" => "Pakistan",
                "region" => "Asia",
                "subregion" => "Southern Asia",
                "timezones" => '[{"zoneName":"Asia/Karachi","gmtOffset":18000,"gmtOffsetName":"UTC+05:00","abbreviation":"PKT","tzName":"Pakistan Standard Time"}]',
                "translations" => '{"kr":"파키스탄","pt-BR":"Paquistão","pt":"Paquistão","nl":"Pakistan","hr":"Pakistan","fa":"پاکستان","de":"Pakistan","es":"Pakistán","fr":"Pakistan","ja":"パキスタン","it":"Pakistan","cn":"巴基斯坦","tr":"Pakistan"}',
                "latitude" => "30.00000000",
                "longitude" => "70.00000000",
                "emoji" => "🇵🇰",
                "emojiU" => "U+1F1F5 U+1F1F0",
                "created_at" => "2018-07-21 07:11:03",
                "updated_at" => "2022-05-21 21:32:07",
                "flag" => 1,
                "wikiDataId" => "Q843",
                "created_by" => 1,
                "updated_by"=> null,
                'status' => 1
            ],
            [
                "name" => "Qatar",
                "iso3" => "QAT",
                "numeric_code" => "634",
                "iso2" => "QA",
                "phone_code" => "974",
                "capital" => "Doha",
                "currency" => "QAR",
                "currency_name" => "Qatari riyal",
                "currency_symbol" => "ق.ر",
                "tld" => ".qa",
                "native" => "قطر",
                "region" => "Asia",
                "subregion" => "Western Asia",
                "timezones" => '[{"zoneName":"Asia/Qatar","gmtOffset":10800,"gmtOffsetName":"UTC+03:00","abbreviation":"AST","tzName":"Arabia Standard Time"}]',
                "translations" => '{"kr":"카타르","pt-BR":"Catar","pt":"Catar","nl":"Qatar","hr":"Katar","fa":"قطر","de":"Katar","es":"Catar","fr":"Qatar","ja":"カタール","it":"Qatar","cn":"卡塔尔","tr":"Katar"}',
                "latitude" => "25.50000000",
                "longitude" => "51.25000000",
                "emoji" => "🇶🇦",
                "emojiU" => "U+1F1F6 U+1F1E6",
                "created_at" => "2018-07-21 07:11:03",
                "updated_at" => "2022-05-21 21:32:07",
                "flag" => 1,
                "wikiDataId" => "Q846",
                "created_by" => 1,
                "updated_by"=> null,
                'status' => 1
            ],
            [
                "name" => "United Arab Emirates",
                "iso3" => "ARE",
                "numeric_code" => "784",
                "iso2" => "AE",
                "phone_code" => "971",
                "capital" => "Abu Dhabi",
                "currency" => "AED",
                "currency_name" => "United Arab Emirates dirham",
                "currency_symbol" => "إ.د",
                "tld" => ".ae",
                "native" => "دولة الإمارات العربية المتحدة",
                "region" => "Asia",
                "subregion" => "Western Asia",
                "timezones" => '[{"zoneName":"Asia/Dubai","gmtOffset":14400,"gmtOffsetName":"UTC+04:00","abbreviation":"GST","tzName":"Gulf Standard Time"}]',
                "translations" => '{"kr":"아랍에미리트","pt-BR":"Emirados árabes Unidos","pt":"Emirados árabes Unidos","nl":"Verenigde Arabische Emiraten","hr":"Ujedinjeni Arapski Emirati","fa":"امارات متحده عربی","de":"Vereinigte Arabische Emirate","es":"Emiratos Árabes Unidos","fr":"Émirats arabes unis","ja":"アラブ首長国連邦","it":"Emirati Arabi Uniti","cn":"阿拉伯联合酋长国","tr":"Birleşik Arap Emirlikleri"}',
                "latitude" => "24.00000000",
                "longitude" => "54.00000000",
                "emoji" => "🇦🇪",
                "emojiU" => "U+1F1E6 U+1F1EA",
                "created_at" => "2018-07-21 07:11:03",
                "updated_at" => "2022-05-21 21:39:27",
                "flag" => 1,
                "wikiDataId" => "Q878",
                "created_by" => 1,
                "updated_by"=> null,
                'status' => 1
            ],
            [
                "name" => "United Kingdom",
                "iso3" => "GBR",
                "numeric_code" => "826",
                "iso2" => "GB",
                "phone_code" => "44",
                "capital" => "London",
                "currency" => "GBP",
                "currency_name" => "British pound",
                "currency_symbol" => "£",
                "tld" => ".uk",
                "native" => "United Kingdom",
                "region" => "Europe",
                "subregion" => "Northern Europe",
                "timezones" => '[{"zoneName":"Europe/London","gmtOffset":0,"gmtOffsetName":"UTC±00","abbreviation":"GMT","tzName":"Greenwich Mean Time"}]',
                "translations" => '{"kr":"영국","pt-BR":"Reino Unido","pt":"Reino Unido","nl":"Verenigd Koninkrijk","hr":"Ujedinjeno Kraljevstvo","fa":"بریتانیای کبیر و ایرلند شمالی","de":"Vereinigtes Königreich","es":"Reino Unido","fr":"Royaume-Uni","ja":"イギリス","it":"Regno Unito","cn":"英国","tr":"Birleşik Krallik"}',
                "latitude" => "54.00000000",
                "longitude" => "-2.00000000",
                "emoji" => "🇬🇧",
                "emojiU" => "U+1F1EC U+1F1E7",
                "created_at" => "2018-07-21 07:11:03",
                "updated_at" => "2022-05-21 21:39:27",
                "flag" => 1,
                "wikiDataId" => "Q145",
                "created_by" => 1,
                "updated_by"=> null,
                'status' => 1
            ],
            [
                "name" => "United States",
                "iso3" => "USA",
                "numeric_code" => "840",
                "iso2" => "US",
                "phone_code" => "1",
                "capital" => "Washington",
                "currency" => "USD",
                "currency_name" => "United States dollar",
                "currency_symbol" => "$",
                "tld" => ".us",
                "native" => "United States",
                "region" => "Americas",
                "subregion" => "Northern America",
                "timezones" => '[{"zoneName":"America/Adak","gmtOffset":-36000,"gmtOffsetName":"UTC-10:00","abbreviation":"HST","tzName":"Hawaii–Aleutian Standard Time"},{"zoneName":"America/Anchorage","gmtOffset":-32400,"gmtOffsetName":"UTC-09:00","abbreviation":"AKST","tzName":"Alaska Standard Time"},{"zoneName":"America/Boise","gmtOffset":-25200,"gmtOffsetName":"UTC-07:00","abbreviation":"MST","tzName":"Mountain Standard Time (North America)"},{"zoneName":"America/Chicago","gmtOffset":-21600,"gmtOffsetName":"UTC-06:00","abbreviation":"CST","tzName":"Central Standard Time (North America)"},{"zoneName":"America/Denver","gmtOffset":-25200,"gmtOffsetName":"UTC-07:00","abbreviation":"MST","tzName":"Mountain Standard Time (North America)"},{"zoneName":"America/Detroit","gmtOffset":-18000,"gmtOffsetName":"UTC-05:00","abbreviation":"EST","tzName":"Eastern Standard Time (North America)"},{"zoneName":"America/Indiana/Indianapolis","gmtOffset":-18000,"gmtOffsetName":"UTC-05:00","abbreviation":"EST","tzName":"Eastern Standard Time (North America)"},{"zoneName":"America/Indiana/Knox","gmtOffset":-21600,"gmtOffsetName":"UTC-06:00","abbreviation":"CST","tzName":"Central Standard Time (North America)"},{"zoneName":"America/Indiana/Marengo","gmtOffset":-18000,"gmtOffsetName":"UTC-05:00","abbreviation":"EST","tzName":"Eastern Standard Time (North America)"},{"zoneName":"America/Indiana/Petersburg","gmtOffset":-18000,"gmtOffsetName":"UTC-05:00","abbreviation":"EST","tzName":"Eastern Standard Time (North America)"},{"zoneName":"America/Indiana/Tell_City","gmtOffset":-21600,"gmtOffsetName":"UTC-06:00","abbreviation":"CST","tzName":"Central Standard Time (North America)"},{"zoneName":"America/Indiana/Vevay","gmtOffset":-18000,"gmtOffsetName":"UTC-05:00","abbreviation":"EST","tzName":"Eastern Standard Time (North America)"},{"zoneName":"America/Indiana/Vincennes","gmtOffset":-18000,"gmtOffsetName":"UTC-05:00","abbreviation":"EST","tzName":"Eastern Standard Time (North America)"},{"zoneName":"America/Indiana/Winamac","gmtOffset":-18000,"gmtOffsetName":"UTC-05:00","abbreviation":"EST","tzName":"Eastern Standard Time (North America)"},{"zoneName":"America/Juneau","gmtOffset":-32400,"gmtOffsetName":"UTC-09:00","abbreviation":"AKST","tzName":"Alaska Standard Time"},{"zoneName":"America/Kentucky/Louisville","gmtOffset":-18000,"gmtOffsetName":"UTC-05:00","abbreviation":"EST","tzName":"Eastern Standard Time (North America)"},{"zoneName":"America/Kentucky/Monticello","gmtOffset":-18000,"gmtOffsetName":"UTC-05:00","abbreviation":"EST","tzName":"Eastern Standard Time (North America)"},{"zoneName":"America/Los_Angeles","gmtOffset":-28800,"gmtOffsetName":"UTC-08:00","abbreviation":"PST","tzName":"Pacific Standard Time (North America)"},{"zoneName":"America/Menominee","gmtOffset":-21600,"gmtOffsetName":"UTC-06:00","abbreviation":"CST","tzName":"Central Standard Time (North America)"},{"zoneName":"America/Metlakatla","gmtOffset":-32400,"gmtOffsetName":"UTC-09:00","abbreviation":"AKST","tzName":"Alaska Standard Time"},{"zoneName":"America/New_York","gmtOffset":-18000,"gmtOffsetName":"UTC-05:00","abbreviation":"EST","tzName":"Eastern Standard Time (North America)"},{"zoneName":"America/Nome","gmtOffset":-32400,"gmtOffsetName":"UTC-09:00","abbreviation":"AKST","tzName":"Alaska Standard Time"},{"zoneName":"America/North_Dakota/Beulah","gmtOffset":-21600,"gmtOffsetName":"UTC-06:00","abbreviation":"CST","tzName":"Central Standard Time (North America)"},{"zoneName":"America/North_Dakota/Center","gmtOffset":-21600,"gmtOffsetName":"UTC-06:00","abbreviation":"CST","tzName":"Central Standard Time (North America)"},{"zoneName":"America/North_Dakota/New_Salem","gmtOffset":-21600,"gmtOffsetName":"UTC-06:00","abbreviation":"CST","tzName":"Central Standard Time (North America)"},{"zoneName":"America/Phoenix","gmtOffset":-25200,"gmtOffsetName":"UTC-07:00","abbreviation":"MST","tzName":"Mountain Standard Time (North America)"},{"zoneName":"America/Sitka","gmtOffset":-32400,"gmtOffsetName":"UTC-09:00","abbreviation":"AKST","tzName":"Alaska Standard Time"},{"zoneName":"America/Yakutat","gmtOffset":-32400,"gmtOffsetName":"UTC-09:00","abbreviation":"AKST","tzName":"Alaska Standard Time"},{"zoneName":"Pacific/Honolulu","gmtOffset":-36000,"gmtOffsetName":"UTC-10:00","abbreviation":"HST","tzName":"Hawaii–Aleutian Standard Time"}]',
                "translations" => '{"kr":"미국","pt-BR":"Estados Unidos","pt":"Estados Unidos","nl":"Verenigde Staten","hr":"Sjedinjene Američke Države","fa":"ایالات متحده آمریکا","de":"Vereinigte Staaten von Amerika","es":"Estados Unidos","fr":"États-Unis","ja":"アメリカ合衆国","it":"Stati Uniti D\'America","cn":"美国","tr":"Amerika"}',
                "latitude" => "38.00000000",
                "longitude" => "-97.00000000",
                "emoji" => "🇺🇸",
                "emojiU" => "U+1F1FA U+1F1F8",
                "created_at" => "2018-07-21 07:11:03",
                "updated_at" => "2022-05-21 21:39:27",
                "flag" => 1,
                "wikiDataId" => "Q30",
                "created_by" => 1,
                "updated_by"=> null,
                'status' => 0
            ]
        ];

        Country::insert($country);
    }
}
